uav_mass: 0.8 # overall mass of the drone

motor_params:
  n_motors: 4
  a:  0.26453
  b: -0.15

# these model parameters can be used when
# - 'attitude rate', and/or
# - 'actuator control'
# are done by the MRS system.
model_params:
  arm_length: 0.135 # [m]
  body_height: 0.07 # [m]

  # The UAV's inertia is approximated as a cilinder using the parameters above
  # Alternatively, you can provide inertia matrix directly using the following parameter:
  inertia_matrix:
    enabled: false
    matrix: []

  propulsion:
    # force [N] = force_constant * rpm^2
    # for 21400 max rpm it is 20,475625 N then the force constant is 0.000000045
    force_constant: 0.00000000843

    # torque [Nm] = torque_constant * force [N]
    torque_constant: 0.012 # 0.014 torque computed from power (efficiency estimated as 85% )

    prop_radius: 0.09 # [m]

    # allocation motors -> torques

    # quadrotor X configuration
    # hexarotor X configuration
    # [roll torque,      [            [RPM_1^2,
    #  pitch torque,  =    Alloc    *  RPM_2^2,
    #  yaw torque,         Matrix       ...
    #  thrust force]              ]    RPM_n_motors^2]
    allocation_matrix: [
        -0.707, 0.707,  0.707, -0.707, # *= force_constant*arm_length
        -0.707, 0.707, -0.707,  0.707, # *= force_constant*arm_length
          -1  ,  -1  ,   1   ,    1  , # *= torque_constant*force_constant
           1  ,   1  ,   1   ,    1  , # *= force_constant
      ]

    rpm:
      min: 2058 # [revolutions/minute]
      max: 41160 # [revolutions/minute]

mrs_uav_managers:
  constraint_manager:
    default_constraints:
      gps_garmin: "medium"
      gps_baro: "medium"
      rtk: "medium"
      aloam: "slow"
      hector_garmin: "slow"
      vio: "slow"
      optflow: "slow"
      other: "slow"
      ground_truth: "medium"

  safety:
    tilt_limit:
      eland:
        enabled: false

      disarm:
        enabled: false

    tilt_error_disarm:
      enabled: false
      timeout: 0.5 # [s] # for how long the error has to be present to disarm
      error_threshold: deg(20) # [rad]

    yaw_error_eland:
      enabled: false
