f550:

  n_motors: 6                # [-]
  mass: 2.3                  # [kg]
  arm_length: 0.27           # [m]
  body_height: 0.1           # [m]
  motor_time_constant: 0.03  # [s]
  air_resistance_coeff: 0.30 # [-]

  propulsion:

    # force [N] = force_constant * rpm^2
    force_constant: 0.00000012216

    # moment [Nm] = moment_constant * force [N]
    moment_constant: 0.07

    prop_radius: 0.11 # [m]

    # allocation motors -> moments

    # hexarotor X configuration
    # [roll torque,      [            [RPM_1^2,
    #  pitch torque,  =    Alloc    *  RPM_2^2,
    #  yaw torque,         Matrix       ...
    #  thrust force]              ]    RPM_n_motors^2]
    allocation_matrix: [
      1, -1, -0.5,  0.5,  0.5,   -0.5, # *= force_constant*arm_length
      0, 0,  -0.87, 0.87, -0.87, 0.87, # *= force_constant*arm_length
      1, -1, 1,     -1,   -1,    1,    # *= moment_constant*force_constant
      1, 1,  1,     1,    1,     1     # *= force_constant
    ]

    rpm:
      min: 1360.0 # [revolutions/minute]
      max: 9068.0 # [revolutions/minute]
