naki:

  n_motors: 8                # [-]
  mass: 7.5                  # [kg]
  arm_length: 0.20           # [m]
  body_height: 0.2           # [m]
  motor_time_constant: 0.03  # [s]
  air_resistance_coeff: 0.30 # [-]

  propulsion:

    # force [N] = force_constant * rpm^2
    force_constant: 0.00000057658

    # moment [Nm] = moment_constant * force [N]
    moment_constant: 0.07

    prop_radius: 0.13 # [m]

    # allocation motors -> moments

    # coaxial octarotor X configuration
    # [roll torque,      [            [RPM_1^2,
    #  pitch torque,  =    Alloc    *  RPM_2^2,
    #  yaw torque,         Matrix       ...
    #  thrust force]              ]    RPM_n_motors^2]
    allocation_matrix: [
      -0.707, 0.707, 0.707,  -0.707, 0.707, -0.707, -0.707, 0.707,  # *= force_constant*arm_length
      -0.707, 0.707, -0.707, 0.707,  0.707, -0.707, 0.707,  -0.707, # *= force_constant*arm_length
      -1,     -1,    1,      1,      1,     1,      -1,     -1,     # *= moment_constant*force_constant
      1,      1,     1,      1,      1,     1,      1,      1,      # *= force_constant
    ]

    rpm:
      min: 956.0  # [revolutions/minute]
      max: 6376.0 # [revolutions/minute]
